# Generated by Django 5.0.3 on 2024-03-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='creationDate',
            field=models.DateTimeField(),
        ),
    ]
