# Generated by Django 5.0.3 on 2024-03-24 19:03

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_mainblogmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainBlogModel',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(default=1, verbose_name='Text'),
            preserve_default=False,
        ),
    ]
