# Generated by Django 5.0.3 on 2024-03-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_mainblogmodel_blogmodel_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='visiting',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
